name: expandable_text_plus
description: A customizable expandable text widget with "Read more / Read less" toggle for Flutter apps.
version: 1.0.0
homepage: https://github.com/HibaChamkhi/expandable_text_plus
repository: https://github.com/HibaChamkhi/expandable_text_plus
issue_tracker: https://github.com/HibaChamkhi/expandable_text_plus/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

